name: Test
on: { push: { branches: [ main ] }, pull_request: { branches: [ main ] } }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - { name: Checkout, uses: actions/checkout@v3.5.3 }
    - { name: Setup Node.js environment, uses: actions/setup-node@v3.8.1, with: { node-version: 18.x } }
    - { name: Setup pnpm, uses: pnpm/action-setup@v2.4.0, with: { version: 8.6.x, run_install: true } }
    - run: pnpm test
